<?php

namespace AppBundle\Repository;

/**
 * AvaibilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvaibilityRepository extends \Doctrine\ORM\EntityRepository
{
}
