<?php

namespace AppBundle\Repository;

/**
 * ProfessionalInformationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalInformationsRepository extends \Doctrine\ORM\EntityRepository
{
}
