<?php

namespace AppBundle\Repository;

/**
 * ProfessionalsCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalsCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
