app:
    resource: "@AppBundle/Controller/"
    type:     annotation

contact:
    resource: "@AppBundle/Controller/Contact"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
